Add marker to reboot test
PelionIoT/e2e-edge-test-suite pull request #22
Opened 2023-04-14 11:04 UTC by JanneKiiskila

This allows you to run the test suite with -m option to exclude the reboot test in case you don't want to do it.

```
pytest -m "not reboot_test"
```

This shows the following output then to indicate that test is skipped.

```
(venv)  13:53 jannek@jannek-P720:/ssd/e2e-edge-test-suite$ pytest  --config_path=config-os2-snap20.json -m "not reboot_test" ====================================================================================================== test session starts ====================================================================================================== platform linux -- Python 3.10.6, pytest-7.2.1, pluggy-0.13.1 rootdir: /ssd/e2e-edge-test-suite
plugins: html-1.22.0, stress-1.0.1, rerunfailures-10.2, repeat-0.9.1, metadata-2.0.2 collected 14 items / 1 deselected / 13 selected
```

I.e. that one case gets deselected.

# Pull request template

Please fill this pull request template to describe your pull request.
If it introduces API breaks please describe it in detail.

## Check list

 ### Testing

 - [x] tests run against live device.

 ### Changelog
 
 - [x] `CHANGELOG.md` updated.

 ### Tagging
 
 - [ ] Remember to tag a new release, if need be.

2023-04-14 11:25 UTC, petedyerarm requested changes

2023-04-14 11:25 UTC, petedyerarm commented on tests/pytest.ini
> +    reboot_test: this test will reboot device (deselect with '-m "not slow"')
```suggestion
    reboot_test: this test will reboot device (deselect with '-m "not reboot_test"')
```

2023-04-14 11:41 UTC, tulsivanol approved these changes

2023-04-14 12:00 UTC, JanneKiiskila commented on tests/pytest.ini
> +    reboot_test: this test will reboot device (deselect with '-m "not slow"')
Ah, good catch. Copy pasta.
Fixed it.

2023-04-14 12:19 UTC, petedyerarm approved these changes
LGTM

2023-04-14 12:36 UTC, JanneKiiskila commented
Still giving me this:

```
======================================================================================================= warnings summary ========================================================================================================
tests/test_websocket_notifications.py:61
  /ssd/e2e-edge-test-suite/tests/test_websocket_notifications.py:61: PytestUnknownMarkWarning: Unknown pytest.mark.reboot_test - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.reboot_test
```

though according to  [this](https://docs.pytest.org/en/stable/how-to/mark.html#registering-marks): the `pytest.ini` change should be enough.

2023-04-21 08:04 UTC, JanneKiiskila commented
Additional commits, lots of rebasing/tidying up to make history more sensible. Please re-review.

2023-04-21 16:47 UTC, petedyerarm approved these changes
LGTM

2023-04-21 21:49 UTC, merged